In [152]:
import os
import numpy as np
import pandas as pd
from sklearn.metrics import pairwise_distances

In [68]:
path = '../Reference_library_reb/'
dirs = os.listdir(path)
dirs = [x for x in dirs if x not in ['.DS_Store', 'Archive for reference data', 'Processed']]

file_list = []
for d in dirs:
    path_2 = path + d + '/Data/Raw/mIRage OPTIR+Raman/'
    dirs_2 = os.listdir(path_2)
    file_list_aux = [x for x in dirs_2 if x[-3:]=="csv"]
    dirs_2 = [[x+'/'+y for y in os.listdir(path_2 + x)] for x in dirs_2 if os.path.isdir(path_2 + x)]
    dirs_3 = []
    if len(dirs_2) > 0:
        for d2 in dirs_2:
            dirs_3 = dirs_3 + d2
    file_list_aux = file_list_aux + [x for x in dirs_3 if x[-3:]=="csv"]
    file_list_aux = [path_2 + x for x in file_list_aux]
    file_list = file_list + file_list_aux

In [124]:
label = ['PP' if 'PP' in x else 
         'PE' if 'PE' in x else 
         'PSL' if 'PSL' in x else 
         'sucrose' if 'sucrose' in x else 
         'NH2SO4' if 'NH2SO4' in x else 'x' for x in file_list]

In [127]:
df_list = []

for f, l in zip(file_list, label):
    df = pd.read_csv(f)
    if df.shape[1] in [5, 7]:
        df = df.iloc[:,:5]
        df.columns = ['Feature ID', 'X', 'Y', 'Size', 'Area']
        df['label'] = l
        df_list.append(df.reset_index(drop=True))
    
pd.concat(df_list,axis=0)

    Feature ID           X           Y      Size      Area    label
0            1    24.66395    0.117739  0.571350  0.256486  sucrose
1            2    28.97935    0.817852  0.992581  0.774089  sucrose
2            3    29.00776    1.046674  2.592466  5.280621  sucrose
3            4    14.23967    2.332775  1.810985  2.576848  sucrose
4            5    49.08243    4.132461  2.306140  4.178596  sucrose
..         ...         ...         ...       ...       ...      ...
17          18  5782.16800 -668.877100  0.956943  0.720219       PP
18          19  5775.81400 -668.340500  1.156402  1.021017       PP
19          20  5778.78600 -663.565700  0.847059  0.538046       PP
20          21  5763.13400 -662.280300  2.565297  5.081783       PP
21          22  5785.56200 -661.321400  2.298840  3.965443       PP

[575 rows x 6 columns]

In [131]:
path = '../MEC_04_010/Raw Data/Stearates/'
dirs = os.listdir(path)

for d in dirs:
    if d[-4:] == 'ptir' or d==".DS_Store":
        del dirs[np.where(np.array(dirs) == d)[0][0]]
        
files_list = []
for d in dirs:
    files = os.listdir(path + d)
    files_list = files_list + [d+'/'+f for f in files if f[-3:] == 'csv']

['Stearic Acid/20240711_AMA_StearicAcid_cc2.csv',
 'Stearic Acid/20240711_AMA_StearicAcid_cc3.csv',
 'Stearic Acid/20240711_AMA_StearicAcid_cc1.csv',
 'Stearic Acid/20240711_AMA_StearicAcid_cc4.csv',
 'Stearic Acid/20240711_AMA_StearicAcid_cc5.csv',
 'Stearic Acid/20240711_AMA_StearicAcid_cc7.csv',
 'Stearic Acid/20240711_AMA_StearicAcid_cc6.csv',
 'Magnesium Stearate/20240705_AMA_MagnesiumStearate_cc1.csv',
 'Magnesium Stearate/20240705_AMA_MagnesiumStearate_cc2.csv',
 'Magnesium Stearate/20240705_AMA_MagnesiumStearate_cc3.csv',
 'Magnesium Stearate/20240705_AMA_MagnesiumStearate_cc7.csv',
 'Magnesium Stearate/20240705_AMA_MagnesiumStearate_cc6.csv',
 'Magnesium Stearate/20240705_AMA_MagnesiumStearate_cc4.csv',
 'Magnesium Stearate/20240705_AMA_MagnesiumStearate_cc5.csv',
 'Magnesium Stearate v2/20240718_AMA_MagnesiumStearate_v2_cc2.csv',
 'Magnesium Stearate v2/20240718_AMA_MagnesiumStearate_v2_cc3.csv',
 'Magnesium Stearate v2/20240718_AMA_MagnesiumStearate_v2_cc1.csv',
 'Magnesium Stearate v2/20240718_AMA_MagnesiumStearate_v2_cc4.csv',
 'Magnesium Stearate v2/20240718_AMA_MagnesiumStearate_v2_cc5.csv',
 'Magnesium Stearate v2/20240718_AMA_MagnesiumStearate_v2_cc6.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc5.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc4.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc6.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc7.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc3.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc2.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc1.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc10.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc9.csv',
 'Stearic Acid v2/20240718_AMA_StearicAcid_v2_cc8.csv',
 'Calcium Stearate/20240706_AMA_CalciumStearate_cc1.csv',
 'Calcium Stearate/20240706_AMA_CalciumStearate_cc2.csv',
 'Calcium Stearate/20240706_AMA_CalciumStearate_cc3.csv',
 'Calcium Stearate/20240706_AMA_CalciumStearate_cc4.csv',
 'Sodium Stearate/20240708_AMA_SodiumStearate_cc5.csv',
 'Sodium Stearate/20240708_AMA_SodiumStearate_cc4.csv',
 'Sodium Stearate/20240708_AMA_SodiumStearate_cc3.csv',
 'Sodium Stearate/20240708_AMA_SodiumStearate_cc2.csv',
 'Sodium Stearate/20240708_AMA_SodiumStearate_cc1.csv',
 'Zinc Stearate/20240706_AMA_ZincStearate_cc2.csv',
 'Zinc Stearate/20240706_AMA_ZincStearate_cc3.csv',
 'Zinc Stearate/20240706_AMA_ZincStearate_cc1.csv',
 'Zinc Stearate/20240706_AMA_ZincStearate_cc4.csv',
 'Zinc Stearate/20240706_AMA_ZincStearate_cc5.csv']

In [154]:
df_list = []
for f in files_list:
    df = pd.read_csv(path + f)
    df = df.rename({'X (um)':'map_x', 'Y (um)':'map_y'}, axis=1)
    df['polymer'] = f.split('/')[0]
    df_list.append(df)
    
df_all = pd.concat(df_list, axis=0).reset_index(drop=True)
df_all

,Feature ID,map_x,map_y,Size (um),Area (um²),Perimeter (um),Circularity,polymer
0,1,5930.142,-2219.792,1.380477,0.668769,5.451191,0.282741,Stearic Acid
1,2,5917.072,-2216.144,3.325841,8.583941,11.396640,0.830290,Stearic Acid
2,3,6046.916,-2211.764,8.534956,56.024180,30.457780,0.758709,Stearic Acid
3,4,6012.269,-2208.111,5.857454,25.878800,30.641770,0.346268,Stearic Acid
4,5,5904.317,-2209.934,5.057017,9.684446,21.329000,0.267442,Stearic Acid
...,...,...,...,...,...,...,...,...
781,28,10424.120,-1465.072,5.199499,21.730750,18.750880,0.776475,Zinc Stearate
782,29,10464.080,-1458.707,5.007634,19.605920,17.202740,0.832317,Zinc Stearate
783,30,10499.340,-1453.225,9.496995,67.689540,47.965360,0.369626,Zinc Stearate
784,31,10487.070,-1444.708,3.422446,8.634733,14.474430,0.517776,Zinc Stearate
785,32,10385.230,-1446.541,7.381638,39.076400,34.665680,0.408518,Zinc Stearate

In [147]:
preposs_data_ir = pd.read_csv('stearates_data_ir_final.csv').iloc[:,-4:]
preposs_data_ir

            map_x        map_y                polymer                       id
0    11231.849609   214.850006  Magnesium Stearate v2  Magnesium Stearate v2_1
1    11279.049805   216.600006  Magnesium Stearate v2  Magnesium Stearate v2_2
2    11255.250000   216.600006  Magnesium Stearate v2  Magnesium Stearate v2_3
3    11216.599609   218.699997  Magnesium Stearate v2  Magnesium Stearate v2_4
4    11348.250000   254.100006  Magnesium Stearate v2  Magnesium Stearate v2_5
..            ...          ...                    ...                      ...
311  10437.250000 -1466.050049          Zinc Stearate        Zinc Stearate_107
312  10423.900391 -1464.800049          Zinc Stearate        Zinc Stearate_108
313  10464.000000 -1458.449951          Zinc Stearate        Zinc Stearate_109
314  10499.500000 -1452.949951          Zinc Stearate        Zinc Stearate_110
315  10385.349609 -1446.599976          Zinc Stearate        Zinc Stearate_112

[316 rows x 4 columns]

In [174]:
spectra_matches_list = []
for p in np.unique(preposs_data_ir['polymer']):
    
    #if coord_df.query('id_file == @id_').shape[0] == 0:
    #    continue
    id_matches = np.argmin(pairwise_distances(preposs_data_ir.query('polymer == @p').loc[:,['map_x', 'map_y']], 
                                              df_all.query('polymer == @p').loc[:,['map_x', 'map_y']]),1)


    coord_matches = df_all.query('polymer == @p').iloc[id_matches, :].reset_index(drop=True)
    spectra_matches = (preposs_data_ir.
                       query('polymer == @p').
                       reset_index(drop=True).
                       merge(coord_matches, left_index=True, right_index=True))
    
    spectra_matches['distance'] = np.sqrt((spectra_matches['map_x_x'] - spectra_matches['map_x_y']) ** 2 + 
                                          (spectra_matches['map_y_x'] - spectra_matches['map_y_y']) ** 2)
    spectra_matches_list.append(spectra_matches)
    #coord_matches = coord_df.iloc[id_matches, :].reset_index(drop=True)
    
spectra_matches_all = pd.concat(spectra_matches_list).reset_index(drop=True)
spectra_matches_all.loc[:, ['id', 'Size (um)', 'Area (um²)']].to_csv('particle_info_stearate.csv')