In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [85]:
dir_name_2 ='results/20251122'
dir_name ='/Users/eochoa/Downloads'

table_raman_spectra_ref = pd.read_csv(dir_name + '/table_raman_spectra_ref.csv')
table_ir_spectra_ref = pd.read_csv(dir_name + '/table_ir_spectra_ref.csv')
all_table_raman_spectra = pd.read_csv(dir_name + '/all_table_raman_spectra.csv')
#all_table_raman_spectra_raw = pd.read_csv(dir_name + '/all_table_raman_spectra_raw.csv')
all_table_ir_spectra = pd.read_csv(dir_name + '/all_table_ir_spectra.csv')

all_table_ir_spectra_org = pd.read_csv(dir_name + '/all_table_ir_spectra.csv')

In [86]:
all_table_ir_spectra_org.shape

(376, 544)

In [74]:
del table_raman_spectra_ref['Unnamed: 0']
del table_ir_spectra_ref['Unnamed: 0']
del all_table_raman_spectra['Unnamed: 0']
del all_table_ir_spectra['Unnamed: 0']
#del all_table_ir_spectra_org['Unnamed: 0']

In [75]:
all_table_ir_spectra.shape, all_table_ir_spectra_org.shape

((376, 543), (376, 543))

In [61]:
all_table_ir_spectra.iloc[np.where([x not in all_table_ir_spectra_org['id'].to_numpy() for x in all_table_ir_spectra['id'].to_numpy()])[0],
                          :]

,981.0,983.0,985.0,987.0,989.0,991.0,993.0,995.0,997.0,999.0,...,2969.0,map_x,map_y,id,background,type,polymer,label,quality,id_ref
199,-1.203187,-1.226992,-1.262271,-1.278407,-1.278353,-1.273805,-1.270323,-1.267642,-1.262672,-1.255807,...,0.012053,13312.400391,-2805.649902,MEC_04_014_DC_Active_20240808_S2_GridSi_202502...,no_background,Active,Polyamide,3,unpaired_ir,Nylon 21. White Toothbrush Fiber.CSV
279,-1.455518,-1.432710,-1.409235,-1.382536,-1.357934,-1.334171,-1.309033,-1.284857,-1.258648,-1.231510,...,0.851954,21137.550781,-641.099976,DC_passive_July2024_I9_20240806_29,no_background,Passive,Polyamide,3,unpaired_ir,Nylon 3. White Fiber.CSV
280,-1.373189,-1.263437,-1.141283,-1.023520,-0.913366,-0.799954,-0.690745,-0.594376,-0.509822,-0.428824,...,0.133483,15151.900391,2048.750000,FHS_passive_August2024_B4_20240911_86,no_background,Passive,Polyamide,3,unpaired_ir,PA 1. Green Film.CSV
281,-1.186609,-1.140262,-1.089327,-1.048833,-1.003167,-0.958174,-0.906512,-0.849176,-0.799140,-0.755431,...,0.641232,15671.099609,2179.050049,FHS_passive_June2024_C3_20240724_108,no_background,Passive,Polyamide,3,unpaired_ir,Nylon 3. White Fiber.CSV
282,-1.446401,-1.428660,-1.403752,-1.374870,-1.341376,-1.302986,-1.266071,-1.232077,-1.194078,-1.150881,...,1.050923,15860.000000,1857.250000,FHS_passive_June2024_C3_20240724_168,no_background,Passive,Polyamide,3,unpaired_ir,Nylon 3. White Fiber.CSV
283,-0.549302,-0.390616,-0.236111,-0.093343,0.046631,0.178896,0.288308,0.376987,0.442704,0.481038,...,-0.056146,9403.849609,-4415.899902,IAO_passive_August2024_K11_20240917_96,no_background,Passive,Polyamide,3,unpaired_ir,PA 1. Green Film.CSV
284,-1.229834,-1.197055,-1.161698,-1.129101,-1.102900,-1.082007,-1.062244,-1.042490,-1.023138,-1.002114,...,0.085959,25835.900391,-3317.399902,IAO_passive_November2024_J4_20241120_158,no_background,Passive,Polyamide,3,unpaired_ir,Nylon 21. White Toothbrush Fiber.CSV

In [45]:
np.where(~ (all_table_ir_spectra['id'] == all_table_raman_spectra['id']))[0].shape

(0,)

In [46]:
np.where(~ (all_table_ir_spectra['id'] == all_table_raman_spectra_raw['id']))[0].shape

(0,)

In [82]:
all_table_ir_spectra.iloc[np.where(~ (all_table_ir_spectra['id'] == all_table_raman_spectra['id']))[0], :].query('quality == "paired"').loc[:, ['id', 'type', 'polymer', 'quality']].reset_index(drop=True)#.to_csv('results/20251122/ids_wrong_IR_Raman_pairing.csv')

,id,type,polymer,quality
0,MEC_04_014_DC_Active_20240808_S4_GridSi_202409...,Active,Polyethylene,paired
1,MEC_04_014_DC_Active_20240808_S4_GridSi_202409...,Active,Polyethylene,paired
2,MEC_04_014_DC_Active_20240808_S4_GridSi_202410...,Active,Polyethylene,paired
3,MEC_04_014_DC_Active_20240808_S4_GridSi_202410...,Active,Polyethylene,paired
4,MEC_04_014_DC_Active_20240808_S6_ThinSi_202410...,Active,Polyethylene,paired
...,...,...,...,...
57,MEC_02_119_DC_Sp_S1_GridSi_20240305_69,Active,Rubber,paired
58,MEC_02_119_DC_Sp_S1_GridSi_20240305_76,Active,Rubber,paired
59,MEC_02_119_DC_Sp_S1_GridSi_20240305_89,Active,Rubber,paired
60,MEC_02_119_DC_Sp_S1_GridSi_20240228_80,Active,Rubber,paired
61,MEC_02_119_DC_Sp_S1_GridSi_20240228_88,Active,Rubber,paired

In [34]:
all_table_ir_spectra

,981.0,983.0,985.0,987.0,989.0,991.0,993.0,995.0,997.0,999.0,...,2967.0,2969.0,map_x,map_y,id,background,type,polymer,label,quality
0,-0.212640,-0.174479,-0.105788,-0.039080,0.021299,0.049276,0.078511,0.115986,0.136854,0.217821,...,-1.247893,-1.280301,7244.899902,-9757.849609,MEC_04_054_Blank_AlSi_Active_20240414_S6_20250...,no_background,Active,Rubber,13,blank_paired
1,-0.220397,-0.175669,-0.167724,0.209750,0.513378,0.665950,0.843135,0.828810,0.604306,0.229003,...,-2.363226,-1.868856,21966.199219,-7305.299805,MEC_04_054_Blank_AlSi_Active_20241212_S2_20250...,no_background,Active,Rubber,13,blank_paired
2,0.596894,0.561581,0.542741,0.539357,0.519304,0.489067,0.463097,0.439478,0.432889,0.428488,...,-0.982735,-1.046789,21850.900391,-7609.299805,MEC_04_054_Blank_AlSi_Active_20241212_S2_20250...,no_background,Active,Rubber,13,blank_paired
3,2.464510,2.457415,2.441527,2.425588,2.408227,2.395241,2.394235,2.402231,2.414369,2.417083,...,-0.621123,-0.624012,22387.349609,-7644.799805,MEC_04_054_Blank_AlSi_Active_20241212_S2_20250...,no_background,Active,Rubber,13,blank_paired
4,2.713120,2.671004,2.696678,2.723194,2.695733,2.739329,2.804828,2.845787,2.828193,2.769634,...,-1.012294,-1.164893,22555.099609,-7100.899902,MEC_04_054_Blank_AlSi_Active_20241212_S2_20250...,no_background,Active,Rubber,13,blank_paired
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,1.704155,1.863528,2.013007,2.180119,2.360239,2.530151,2.691442,2.855446,3.017855,3.169760,...,-0.609475,-0.565994,15158.099609,1873.650024,FHS_passive_June2024_C3_20240724_67,no_background,Passive,Rubber,13,unpaired_ir
372,0.889995,1.017866,1.153865,1.280584,1.402447,1.524125,1.644307,1.759743,1.870957,1.976088,...,-0.677505,-0.702116,15728.849609,2127.149902,FHS_passive_June2024_C3_20240724_104,no_background,Passive,Rubber,13,unpaired_ir
373,2.518238,2.642467,2.621573,2.608126,2.646242,2.651068,2.561229,2.442469,2.384019,2.380291,...,-0.543246,-0.554664,6068.350098,-1714.650024,DC_passive_June2024_I7_20240717_20,no_background,Passive,Rubber,13,unpaired_ir
374,2.155801,2.290585,2.410242,2.521640,2.616607,2.694819,2.773484,2.846353,2.910927,2.965043,...,-0.416020,-0.443815,6260.600098,-1910.500000,DC_passive_June2024_I7_20240717_75,no_background,Passive,Rubber,13,unpaired_ir
375,0.900933,0.924863,0.955846,0.972523,0.949230,0.923993,0.920411,0.907966,0.885670,0.878124,...,-0.445294,-0.592401,21389.250000,-866.000000,IAO_passive_June2024_G7_20240725_12,no_background,Passive,Rubber,13,unpaired_ir

In [10]:
table_ir_spectra_ref

,id,981.0,983.0,985.0,987.0,989.0,991.0,993.0,995.0,997.0,...,2957.0,2959.0,2961.0,2963.0,2965.0,2967.0,2969.0,map_x,map_y,polymer
0,R 6. Black Bike Tire Fragment.CSV,1.370935,1.454688,1.533022,1.619688,1.714374,1.809468,1.897331,1.992754,2.101596,...,-0.630891,-0.634651,-0.643791,-0.673699,-0.729238,-0.789812,-0.842691,0,0,Rubber
1,R 5. Black Michelin Tire Fragment.CSV,0.282497,0.295271,0.321757,0.365226,0.424624,0.488366,0.532329,0.541397,0.519073,...,-0.247124,-0.270053,-0.298305,-0.330352,-0.364853,-0.397433,-0.425012,0,0,Rubber
2,R 14. Green Rubber Fragment.CSV,0.693482,0.660028,0.663076,0.705895,0.784823,0.897033,1.044127,1.231044,1.458821,...,-0.376654,-0.389896,-0.411740,-0.440165,-0.474923,-0.511714,-0.547139,0,0,Rubber
3,R 4. Black Bridgestone Tire Fragment.CSV,0.482529,0.485387,0.500185,0.529376,0.570316,0.615960,0.651005,0.669270,0.674512,...,-0.443561,-0.455088,-0.468597,-0.485757,-0.506625,-0.527800,-0.546363,0,0,Rubber
4,R 9. Grey Rubber Fragment.CSV,1.284718,1.399636,1.532527,1.686089,1.863279,2.070102,2.307759,2.582352,2.892973,...,-0.145861,-0.172316,-0.202145,-0.236513,-0.274697,-0.313781,-0.350221,0,0,Rubber
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,R 12. Red Rubber Fragment.CSV,0.870697,0.882504,0.928096,1.009076,1.124462,1.276259,1.466288,1.699572,1.976110,...,-0.337468,-0.344296,-0.356592,-0.377344,-0.406548,-0.436856,-0.465068,0,0,Rubber
372,PVC 1. Clear Fragment.CSV,0.746498,0.764578,0.784117,0.805544,0.829042,0.850556,0.865678,0.871133,0.866313,...,0.632813,0.658160,0.673642,0.667802,0.634114,0.572885,0.488790,0,0,Polyvinyl Chloride
373,R 9. Grey Rubber Fragment.CSV,1.284718,1.399636,1.532527,1.686089,1.863279,2.070102,2.307759,2.582352,2.892973,...,-0.145861,-0.172316,-0.202145,-0.236513,-0.274697,-0.313781,-0.350221,0,0,Rubber
374,R 13. Pink Rubber Fragment.CSV,0.047961,0.067686,0.095119,0.129901,0.172313,0.220769,0.271394,0.328023,0.392121,...,-0.117166,-0.142188,-0.175826,-0.224343,-0.287433,-0.357290,-0.426508,0,0,Rubber
375,R 17. Grey Rubber Paving.CSV,-0.753309,-0.703975,-0.649127,-0.589600,-0.532562,-0.479526,-0.444238,-0.419774,-0.398495,...,0.547923,0.470099,0.360967,0.219370,0.043412,-0.121142,-0.251024,0,0,Rubber