In [84]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [85]:
local_path = '/Users/eochoa/Documents/Research_Abuj/M4AM/spectral_libraries/'
samples_ma_dict = pd.read_csv('./Mendeley_data/samples_ multil_assembly_dict.csv')
polymer_dict = pd.read_csv('./Mendeley_data/polymer_dict.csv')

path = './Mendeley_data/83my5tpmpw-2/'

file_name_list = os.listdir(path=path)

df_list = list()
for f in file_name_list:
    
    df = pd.read_csv(path + f, sep = ',', header=None, skiprows=5)
    df.insert(2, "file_name", [f]*len(df), True) 
    df = df.loc[:, [0, 1, 'file_name']]
    df_list.append(df)
    
df_spectra = pd.concat(df_list, axis=0)
df_spectra.columns = ['wavelength', 'intensity', 'file_name']

samples_ma_dict = pd.melt(samples_ma_dict, id_vars='sample')
samples_ma_dict.rename(columns={'variable':'multil_assembly', 
                                'value':'polymer_short'}, inplace=True)
samples_ma_dict = pd.merge(samples_ma_dict, polymer_dict, how='left')

file_name_split = [x.split() for x in np.sort(file_name_list)]
file_name_df = pd.DataFrame([x[0:2] if (x[0][0:2] != '20' and x[1][:3] != 'mid') 
 else [x[0], 'ml' + x[2][0]] if (x[0][0:2] != '20' and x[1] == 'midlayer')
 else [x[0], 'ml' + x[3]] if (x[0][0:2] != '20' and x[1] == 'mid')
 else [x[1][1:], x[2][0:x[2].find('_')]] if x[2][0:x[2].find('_')] != 'printed.1'
 else [x[1][1:], x[2][0:x[2].find('.')]] for x in file_name_split])

file_name_df.columns = ['sample', 'multil_assembly']
file_name_df['file_name'] = np.sort(file_name_list)
file_name_df = file_name_df.astype({'sample':int})
file_name_df = pd.merge(file_name_df, samples_ma_dict, on=['sample', 'multil_assembly'])

df_spectra_1 = pd.merge(df_spectra, file_name_df.loc[:,['file_name', 'polymer']])
df_spectra_1['data_source'] = 'food_packaging'
df_spectra_1['type_sprectra'] = 'FTIR'

PUR - Polyester Polyurethane both?

In [86]:
samples_ma_dict.drop_duplicates(['polymer_short','polymer'])

    sample multil_assembly polymer_short                               polymer
0        1         printed            PP                         Polypropylene
2        3         printed           PET            Polyethylene Terephthalate
19       1             ml1          LDPE              Low Density Polyethylene
23       5             ml1            PE                          Polyethylene
28      12             ml1           PUR                Polyester Polyurethane
38       1             ml2         m-PET  Metalized Polyethylene Terephthalate
40       3             ml2        m-LDPE    Metalized Low Density Polyethylene
41       4             ml2          m-PP               Metalized Polypropylene
47      12             ml2         m-EVA      Metalized Ethylene Vinyl Alcohol
56      11             ml2         m-SBR    Metalized Styrene Butadiene Rubber
57       1             fcl         LLDPE       Linear Low Density Polyethylene

In [87]:
polymer_dict

   polymer_short                               polymer
0             PP                         Polypropylene
1             PE                          Polyethylene
2           LDPE              Low Density Polyethylene
3            PET            Polyethylene Terephthalate
4          LLDPE       Linear Low Density Polyethylene
5            PUR                Polyester Polyurethane
6            EVA                Ethylene Vinyl Alcohol
7            SBR              Styrene Butadiene Rubber
8          m-PET  Metalized Polyethylene Terephthalate
9         m-LDPE    Metalized Low Density Polyethylene
10          m-PP               Metalized Polypropylene
11         m-EVA      Metalized Ethylene Vinyl Alcohol
12         m-SBR    Metalized Styrene Butadiene Rubber

In [88]:
path = './Mendeley_data/kpygrf9fg6-1/'
polymer_dict = pd.read_csv('./dict_polymers.csv')
file_name_list = os.listdir(path=path)

polymer_dict = (polymer_dict.
 rename(columns={'pol_short_names': 'polymer_short'}).
 drop('Unnamed: 0', axis=1))

df_list = list()
for f in file_name_list:
    
    if f[-3:] == "txt":
        df = pd.read_csv(path + f, sep = '\t', header=None, skiprows=5)
        df.insert(2, "file_name", [f]*len(df), True) 
        df_list.append(df)
df_spectra = pd.concat(df_list, axis=0)
df_spectra.columns = ['wavelength', 'intensity', 'ID']
df_spectra['ID'] = [x[:-4] for x in df_spectra['ID']]
files_table = pd.read_excel(path + '/content.xlsx',
              skiprows=1)
files_table = files_table.query('type != "type"').loc[:, ['ID', 'type']]
df_spectra = pd.merge(df_spectra, files_table, on = "ID")
df_spectra.rename(columns={'type': 'polymer_short'}, inplace=True)
df_spectra = pd.merge(df_spectra, polymer_dict, how='left').drop('polymer_short', axis=1)
df_spectra_2 = df_spectra.rename(columns={'ID': 'file_name'})
df_spectra_2['data_source'] = 'RDWP'
df_spectra_2['type_sprectra'] = 'raman'

In [89]:
for f in file_name_list:
    
    if f[-3:] == "txt":
        df = pd.read_csv(path + f, sep = '\t', header=None, skiprows=5)
        df.insert(2, "file_name", [f]*len(df), True) 
        df_list.append(df)
df_spectra = pd.concat(df_list, axis=0)

df_spectra.columns = ['wavelength', 'intensity', 'ID']
df_spectra['ID'] = [x[:-4] for x in df_spectra['ID']]
files_table = pd.read_excel(path + '/content.xlsx',
              skiprows=1)
files_table = files_table.query('type != "type"').loc[:, ['ID', 'type']]

df_spectra

       wavelength  intensity      ID
0      216.293452     928.50  wea-56
1      219.175678     947.50  wea-56
2      222.056878     937.75  wea-56
3      224.937050     941.25  wea-56
4      227.816198     933.00  wea-56
...           ...        ...     ...
1403  3492.404511    3364.75  wea-73
1404  3494.304539    3389.00  wea-73
1405  3496.204071    3433.25  wea-73
1406  3498.103107    3397.25  wea-73
1407  3500.001648    3377.50  wea-73

[487294 rows x 3 columns]

In [90]:
polymer_dict

   polymer_short                          polymer
0            ABS  Acrylonitrile Butadiene Styrene
1        Acrylic                          Acrylic
2              C                           Cotton
3             CA                Cellulose Acetate
4         Cotton                           Cotton
5            EAA            Ethylene Acrylic Acid
6            EVA       Polyethylene Vinyl Acetate
7          Nylon                            Nylon
8             PA                        Polyamide
9            PBT       Polybutylene Terephthalate
10            PC                    Polycarbonate
11            PE                     Polyethylene
12           PEA             Polyethylene Adipate
13           PET       Polyethylene Terephthalate
14          PEVA       Polyethylene Vinyl Acetate
15           PLA                  Polylactic acid
16          PMMA          Polymethyl Methacrylate
17            PP                    Polypropylene
18            PS                      Polystyrene
19            PU                     Polyurethane
20           PVA                Polyvinyl Acetate
21           PVC               Polyvinyl Chloride
22     Polyester                        Polyester
23             R         Styrene-butadiene Rubber
24            SR                               SR

In [91]:
df_flopp = pd.read_csv('./processed_data/df_flopp.csv').drop(columns=['Unnamed: 0', 'color'])
df_flopp_e = pd.read_csv('./processed_data/df_flopp_e.csv').drop(columns=['Unnamed: 0', 'color'])
df_slopp = pd.read_csv('./processed_data/df_slopp.csv').drop(columns=['Unnamed: 0', 'color'])
df_slopp_e = pd.read_csv('./processed_data/df_slopp_e.csv').drop(columns=['Unnamed: 0', 'color'])

df_flopp['data_source'] = 'flopp'
df_flopp_e['data_source'] = 'flopp_e'
df_slopp['data_source'] = 'slopp'
df_slopp_e['data_source'] = 'slopp_e'

df_flopp['type_sprectra'] = 'FTIR'
df_flopp_e['type_sprectra'] = 'FTIR'
df_slopp['type_sprectra'] = 'raman'
df_slopp_e['type_sprectra'] = 'raman'

In [92]:
MPdatabase = pd.read_csv('./processed_data/MPdatabase_Rpackage.csv').drop(columns='Unnamed: 0')
MPdatabase['data_source'] = 'Rpackage'
MPdatabase['type_sprectra'] = 'raman'

/var/folders/9g/bj6gc6z17_1fyb7lx57xf04m0000gs/T/ipykernel_11103/3336797354.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  MPdatabase = pd.read_csv('./processed_data/MPdatabase_Rpackage.csv').drop(columns='Unnamed: 0')

In [93]:
df_spectra = pd.concat([df_spectra_1, 
                        df_spectra_2, 
                        df_flopp,
                        df_flopp_e,
                        df_slopp,
                        df_slopp_e,
                        MPdatabase])

In [94]:
df_spectra_count = (df_spectra.
                    groupby(['type_sprectra', 'data_source']).
                    nunique().
                    loc[:,['file_name', 'polymer']])

df_spectra_minmax = (df_spectra.
                    groupby(['type_sprectra', 'data_source']).
                    agg({'wavelength':['min', 'max'],
                         'intensity':['min', 'max']}).
                     apply(round))

df_spectra_summary = pd.concat([df_spectra_count,
                               df_spectra_minmax], axis=1)

df_spectra_summary.columns = ['count_spectra', 
                              'count_polymer', 
                              'min_wavelength', 
                              'max_wavelength',
                              'min_intensity',
                              'max_intensity']
df_spectra_summary

                              count_spectra  count_polymer  min_wavelength  \
type_sprectra data_source
FTIR          flopp                     186             16           399.0
              flopp_e                   195             15           399.0
              food_packaging             96             11           650.0
raman         RDWP                      173              8           212.0
              Rpackage                  356             11           101.0
              slopp                     148             15             0.0
              slopp_e                   113             20            52.0

                              max_wavelength  min_intensity  max_intensity
type_sprectra data_source
FTIR          flopp                   4002.0            0.0          114.0
              flopp_e                 4002.0            0.0          110.0
              food_packaging          3999.0           17.0          102.0
raman         RDWP                    3500.0          544.0        65535.0
              Rpackage                3201.0       -40691.0      4186827.0
              slopp                   3499.0         -470.0        46033.0
              slopp_e                 4000.0         -235.0        57414.0

In [95]:
df_spectra_count = (df_spectra.
                    groupby(['polymer']).
                    nunique().
                    loc[:,['file_name', 'data_source', 'type_sprectra']])

df_spectra_count

#df_spectra_minmax = (df_spectra.
#                    groupby(['type_sprectra', 'data_source']).
#                    agg({'wavelength':['min', 'max'],
#                         'intensity':['min', 'max']}).
#                     apply(round))

#df_spectra_summary = pd.concat([df_spectra_count,
#                               df_spectra_minmax], axis=1)

#df_spectra_summary.columns = ['count_spectra', 
#                              'count_polymer', 
#                              'min_wavelength', 
#                              'max_wavelength',
 #                             'min_intensity',
 #                             'max_intensity']
#df_spectra_summary

,file_name,data_source,type_sprectra
polymer,,,
Acrylic,19,3,2
Acrylonitrile Butadiene Styrene,28,6,2
Cellulose Acetate,9,3,2
Cotton,42,3,2
Dyed Cellulose,5,1,1
Ethylene Acrylic Acid,1,1,1
Linear Low Density Polyethylene,9,1,1
Low Density Polyethylene,10,1,1
Metalized Ethylene Vinyl Alcohol,1,1,1
Metalized Low Density Polyethylene,1,1,1
Metalized Polyethylene Terephthalate,13,1,1
Metalized Polypropylene,8,1,1
Metalized Styrene Butadiene Rubber,1,1,1
Nylon,12,1,1
Polyamide,28,5,2
Polybutylene Terephthalate,2,2,1
Polycarbonate,21,6,2
Polyester,36,3,2
Polyester Polyurethane,10,1,1
Polyethylene,197,7,2
Polyethylene Adipate,1,1,1
Polyethylene Terephthalate,74,7,2
Polyethylene Terephthalate-co-Polycarbonate,1,1,1
Polyethylene Vinyl Acetate,20,3,2
Polyethylene-co-Polypropylene,3,1,1
Polylactic acid,8,1,1
Polymethyl Methacrylate,7,4,2
Polypropylene,215,7,2
Polystyrene,50,6,2
Polystyrene-co-Polyvinyl Chloride,1,1,1
Polysulfone,1,1,1
Polyurethane,31,4,2
Polyvinyl Acetate,2,1,1
Polyvinyl Chloride,44,6,2
Rubber,19,2,2
Silicone Rubber,1,1,1

In [97]:
df_spectra

,wavelength,intensity,file_name,polymer,data_source,type_sprectra
0,650.420453,98.655435,14 printed 20.2.2020_2020-02-20t13-18-11.csv,Polypropylene,food_packaging,FTIR
1,652.284122,98.633284,14 printed 20.2.2020_2020-02-20t13-18-11.csv,Polypropylene,food_packaging,FTIR
2,654.147790,98.620059,14 printed 20.2.2020_2020-02-20t13-18-11.csv,Polypropylene,food_packaging,FTIR
3,656.011459,98.597633,14 printed 20.2.2020_2020-02-20t13-18-11.csv,Polypropylene,food_packaging,FTIR
4,657.875128,98.590591,14 printed 20.2.2020_2020-02-20t13-18-11.csv,Polypropylene,food_packaging,FTIR
...,...,...,...,...,...,...
1237451,3197.892000,0.000000,PY97,NaN,Rpackage,raman
1237452,3198.717000,0.000000,PY97,NaN,Rpackage,raman
1237453,3199.542000,0.000000,PY97,NaN,Rpackage,raman
1237454,3200.366000,0.000000,PY97,NaN,Rpackage,raman
1237455,3201.191000,0.000000,PY97,NaN,Rpackage,raman

In [96]:
df_spectra.to_csv(local_path + 'spectral_data_all.csv')