In [33]:
import spectrochempy as scp

In [34]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

In [35]:
dir_paht = 'Paint_MP_library/spa files/'
files_list = os.listdir(dir_paht)

In [36]:
X = [scp.read_omnic(dir_paht+x) for x in os.listdir(dir_paht)]

In [37]:
inventory = pd.read_excel('Paint_MP_library/paint-library-inventory.xlsx', skiprows=[0])
inventory = inventory.loc[:,['Polymer','.SPA file name']]
inventory['.SPA file name'] = inventory['.SPA file name'].str.lower()

In [45]:
inventory.groupby('Polymer').count()

                                                    .SPA file name
Polymer
Alkyd Resin                                                      5
Alkyd Varnish                                                    2
Alkyd resin                                                      1
Poly(vinyl acetate:ethylene)                                     4
Polyacrylate                                                     5
Unknown                                                          2
Vinyl Chloride Vinyl Acetate Maleic Acid Terpol...               2

In [39]:
df = pd.DataFrame({X[i].name+'.spa':X[i].data[0] for i in range(21)})
df['wavelength'] = X[0].x.data
df.columns = df.columns.str.lower()
df = df.melt('wavelength')
df = pd.merge(df, inventory, how='left', left_on='variable', right_on='.SPA file name')
df = df.drop(columns='.SPA file name')
df.columns = ['wavelength', 'file_name', 'intensity', 'polymer']

In [43]:
df.groupby('polymer').count()

,wavelength,file_name,intensity
polymer,,,
Alkyd Resin,6900,6900,6900
Alkyd Varnish,3450,3450,3450
Alkyd resin,1725,1725,1725
Poly(vinyl acetate:ethylene),5175,5175,5175
Polyacrylate,6900,6900,6900
Unknown,3450,3450,3450
Vinyl Chloride Vinyl Acetate Maleic Acid Terpolymer,1725,1725,1725

In [31]:
df = pd.DataFrame({X[i].name+'.spa':X[i].data[0] for i in range(21)})
df['wavelength'] = X[0].x.data
df.columns = df.columns.str.lower()
df = df.melt('wavelength')
df = pd.merge(df, inventory, how='left', left_on='variable', right_on='.SPA file name')
df = df.drop(columns='.SPA file name')
df.columns = ['wavelength', 'file_name', 'intensity', 'polymer']
df['data_source'] = 'Paint_MP_library'
df['type_sprectra'] = 'FTIR'
df = df.loc[:, ['wavelength', 'intensity', 'file_name', 'polymer', 'data_source', 'type_sprectra']]
df.to_csv('processed_data/paint_MP_library.csv')

In [159]:
df = pd.DataFrame({X[i].name+'.spa':X[i].data[0] for i in range(21)})
df['wavelength'] = X[0].x.data
df.columns = df.columns.str.lower()
df = df.melt('wavelength')
df = pd.merge(df, inventory, how='left', left_on='variable', right_on='.SPA file name')
df = df.drop(columns='.SPA file name')
df.columns = ['wavelength', 'file_name', 'intensity', 'polymer']
df.to_csv('processed_data/paint_MP_library.csv')